language: node_js

node_js:
  - "9.6.1"
before_install:
  - npm i -g npm@5.6.0
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test
before_script:
  - chmod 0755 ./node_modules/.bin/mocha
after_success:
  - npm run coveralls
  - npm run coverage